# Generated by Django 2.0.2 on 2018-05-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ptime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
