# Generated by Django 2.0.2 on 2018-05-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180511_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
